token: y0__xCK5KlCGN74BiDP-dLnFTDgxrXhB__ZzFk1Mvm9o8kT2R4VB2w7AUn-
buffer-size-ms: 80
rewind-duration-s: 5
volume: 1
volume-step: 0.05
suppress-errors: false
show-lyrics: true
cache-tracks: likes
cache-dir: Music/Yandex
search:
    artists: true
    albums: false
    playlists: false
controls:
    quit: q
    apply: enter
    cancel: esc
    cursor-up: k
    cursor-down: j
    reload: r
    show-all-kyes: '?'
    playlists-up: pgup
    playlists-down: pgdown
    playlists-rename: c
    playlists-hide: ctrl+b
    tracks-like: f
    tracks-add-to-playlist: a
    tracks-remove-from-playlist: shift+a
    tracks-share: ctrl+s
    tracks-shuffle: ctrl+x
    tracks-search: /
    tracks-hide: ctrl+t
    player-pause: ' '
    player-next: "n"
    player-previous: p
    player-rewind-forward: l
    player-rewind-backward: h
    player-like: F
    player-cache: S
    player-vol-up: +,=
    player-vol-down: '-'
    player-toggle-lyrics: t
    player-hide: ctrl+p
colors:
    accent: '#FC0'
    error: '#F33'
    background: '#6b6b6b'
    active-text: '#EEE'
    normal-text: '#CCC'
    inactive-text: '#888'
    lyrics-previous: '#444'
    lyrics-current: '#EEE'
    lyrics-next: '#777'
